services:
  - type: web
    name: fitcode-frontend
    env: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: dist
    buildFilter:
      paths:
        - "src/**"
        - "public/**"
        - "vite.config.js"
        - "package.json"
        - "pnpm-lock.yaml"
 